image: barichello/godot-ci:4.4.1

variables:
  EXPORT_NAME: gittest1

stages:
  -export

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  
linux:
  stage: export
  script:
    - mkdir -v -p build/linux
    - godot -v --export "Linux" ./build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux